---

- name: Palo Alto Playbook
  hosts: palo
  gather_facts: false
  connection: local

  collections:
    - paloaltonetworks.panos


  vars:
    palo_provider:
      ip_address: '10.209.8.11'
      username:
      password:
      
    client_dev_vpc_cidr: "20.20.20.20/32"
    
    frontend_subnet_object_details:
      - name: dev-frontend-a
        value: 1.1.1.1
      - name: dev-frontend-b
        value: 2.2.2.2
        
    backend_subnet_object_details:
      - name: dev-backend-a
        value: 7.7.7.7
      - name: dev-backend-b
        value: 8.8.8.8  
        
    splunk_dev_deployment_server: splunk-dp-10.192.224.149
    
    splunk_dev_heavy_forwarder: splunk-fw-10.192.224.168    
       
    newrelic_proxy_forwarder: newrelic-proxy-forwarder-10.192.224.21
    
    wafv2: wafv2.us-east-1.amazonaws.com

    client_name: ansible
    
    tag_name: ANSIBLE

    ticket_id: 1234

    existing_rule: gers-V3LODEV-SMTP.v3locitydev.com

    device_group: vitech-firewalls

  tasks:
    - name: Create Client Dev Frontend Subnet Address Objects
      panos_address_object:
        provider: '{{ palo_provider }}'
        name: '{{ client_name }}-{{item.name}}'
        value: '{{item.value}}'
        device_group: '{{ device_group }}'
      loop: "{{ frontend_subnet_object_details }}"

    - name: Create Client Dev Backend Subnet Address Objects
      panos_address_object:
        provider: '{{ palo_provider }}'
        name: '{{ client_name }}-{{item.name}}'
        value: '{{item.value}}'
        device_group: '{{ device_group }}'
      loop: "{{ backend_subnet_object_details }}"
      
    - name: Create Client DBM EC2 Address Object
      panos_address_object:
        provider: '{{ palo_provider }}'
        name: '{{ client_name }}-dbm.v3locitydev.com'
        address_type: 'fqdn'
        value: '{{ client_name }}-dbm.v3locitydev.com'
        device_group: '{{ device_group }}'
      
    - name: Create Client Frontend Subnet Address Object Group
      panos_address_group:
        provider: '{{ palo_provider }}'
        name: '{{ client_name }}-frontend-subs'
        state: merged
        static_value: ['{{ client_name }}-{{item.name}}']
        device_group: '{{ device_group }}'
      loop: "{{ frontend_subnet_object_details }}"

    - name: Cerate Client Backend Subnet Address Object Group
      panos_address_group:
        provider: '{{ palo_provider }}'
        name: '{{ client_name }}-backend-subs'
        state: merged
        static_value: ['{{ client_name }}-{{item.name}}']
        device_group: '{{ device_group }}'
      loop: "{{ backend_subnet_object_details }}"

    - name: Create tag object 
      panos_tag_object:
        provider: '{{ palo_provider }}'
        name: '{{ tag_name }}'
        color: 'red'
        device_group: '{{ device_group }}'
        
    - name: From corp subs to client backend subs
      panos_security_rule:
        provider: '{{ palo_provider }}'
        rule_name: 'From corp subs to client backend subs - {{ client_name }}'
        description: '{{ ticket_id }}'
        source_zone: ['inside']
        destination_zone: ['inside']
        source_ip: ['vitech-corp-subnets']
        destination_ip: ['{{ client_name }}-backend subs']
        tag_name: ['{{ tag_name }}']
        group_tag: '{{ tag_name }}'
        service: ['corp-dev-ports']
        action: 'allow'
        group_profile: 'strict-security-profile'
        log_start: 'yes'
        location: 'before'
        existing_rule: '{{ existing_rule }}'
        log_setting: 'log-forwarding-panorama'
        device_group: '{{ device_group }}'
        
    - name: To newrelic forwarder from clinet backend subs
      panos_security_rule:
        provider: '{{ palo_provider }}'
        rule_name: 'To newrelic forwarder from clinet backend subs - {{ client_name }}'
        description: '{{ ticket_id }}'
        source_zone: ['inside']
        destination_zone: ['inside']
        source_ip: ['{{ client_name }}-backend subs']
        destination_ip: ['{{ newrelic_proxy_forwarder }}']
        tag_name: ['{{ tag_name }}']
        group_tag: '{{ tag_name }}'
        service: ['tcp-3428']
        action: 'allow'
        group_profile: 'strict-security-profile'
        log_start: 'yes'
        location: 'before'
        existing_rule: '{{ existing_rule }}'
        log_setting: 'log-forwarding-panorama'
        device_group: '{{ device_group }}'
        
    - name: To v3locity dev smtp from client backend subs
      panos_security_rule:
        provider: '{{ palo_provider }}'
        rule_name: 'To v3locity dev smtp from client backend subs - {{ client_name }}'
        description: '{{ ticket_id }}'
        source_zone: ['inside']
        destination_zone: ['inside']
        source_ip: ['{{ client_name }}-backend subs']
        destination_ip: ['v3lodev-smtp.v3locitydev.com']
        tag_name: ['{{ tag_name }}']
        group_tag: '{{ tag_name }}'
        service: ['tcp-587']
        action: 'allow'
        group_profile: 'strict-security-profile'
        log_start: 'yes'
        location: 'before'
        existing_rule: '{{ existing_rule }}'
        log_setting: 'log-forwarding-panorama'
        device_group: '{{ device_group }}'
        
    - name: To splunk dev heavy forwarder from client backend subs
      panos_security_rule:
        provider: '{{ palo_provider }}'
        rule_name: 'To splunk dev heavy forwarder from client backend subs - {{ client_name }}'
        description: '{{ ticket_id }}'
        source_zone: ['inside']
        destination_zone: ['inside']
        source_ip: ['{{ client_name }}-backend subs']
        destination_ip: ['{{ splunk_dev_heavy_forwarder }}']
        tag_name: ['{{ tag_name }}']
        group_tag: '{{ tag_name }}'
        service: ['tcp-9997']
        action: 'allow'
        group_profile: 'strict-security-profile'
        log_start: 'yes'
        location: 'before'
        existing_rule: '{{ existing_rule }}'
        log_setting: 'log-forwarding-panorama'
        device_group: '{{ device_group }}'
        
    - name: To splunk_deployment_server from client backend subs
      panos_security_rule:
        provider: '{{ palo_provider }}'
        rule_name: 'To splunk_deployment_server from client backend subs - {{ client_name }}'
        description: '{{ ticket_id }}'
        source_zone: ['inside']
        destination_zone: ['inside']
        source_ip: ['{{ client_name }}-backend subs']
        destination_ip: ['{{ splunk_dev_deployment_server }}']
        tag_name: ['{{ tag_name }}']
        group_tag: '{{ tag_name }}'
        service: ['TCP-8089']
        action: 'allow'
        group_profile: 'strict-security-profile'
        log_start: 'yes'
        location: 'before'
        existing_rule: '{{ existing_rule }}'
        log_setting: 'log-forwarding-panorama'
        device_group: '{{ device_group }}'
        
    - name: From ng2 dev subs to client backend subs
      panos_security_rule:
        provider: '{{ palo_provider }}'
        rule_name: 'From ng2 dev subs to client backend subs- {{ client_name }}'
        description: '{{ ticket_id }}'
        source_zone: ['inside']
        destination_zone: ['inside']
        source_ip: ['ng2-dev-priv-subs']
        destination_ip: ['{{ client_name }}-backend subs']
        tag_name: ['{{ tag_name }}']
        group_tag: '{{ tag_name }}'
        service: ['service-https']
        action: 'allow'
        group_profile: 'strict-security-profile'
        log_start: 'yes'
        location: 'before'
        existing_rule: '{{ existing_rule }}'
        log_setting: 'log-forwarding-panorama'
        device_group: '{{ device_group }}'
        
    - name: From art dev subs to client backend subs
      panos_security_rule:
        provider: '{{ palo_provider }}'
        rule_name: 'From art dev subs to client backend subs - {{ client_name }}'
        description: '{{ ticket_id }}'
        source_zone: ['inside']
        destination_zone: ['inside']
        source_ip: ['art-dev-priv-subs']
        destination_ip: ['{{ client_name }}-backend subs']
        tag_name: ['{{ tag_name }}']
        group_tag: '{{ tag_name }}'
        service: ['tcp-443-5432']
        action: 'allow'
        group_profile: 'strict-security-profile'
        log_start: 'yes'
        location: 'before'
        existing_rule: '{{ existing_rule }}'
        log_setting: 'log-forwarding-panorama'
        device_group: '{{ device_group }}'
        
    - name: From splunk deployment server to client backend subs
      panos_security_rule:
        provider: '{{ palo_provider }}'
        rule_name: 'From splunk deployment server to client backend subs - {{ client_name }}'
        description: '{{ ticket_id }}'
        source_zone: ['inside']
        destination_zone: ['inside']
        source_ip: ['{{ splunk_dev_deployment_server }}']
        destination_ip: ['{{ client_name }}-backend subs']
        tag_name: ['{{ tag_name }}']
        group_tag: '{{ tag_name }}'
        service: ['TCP-8089']
        action: 'allow'
        group_profile: 'strict-security-profile'
        log_start: 'yes'
        location: 'before'
        existing_rule: '{{ existing_rule }}'
        log_setting: 'log-forwarding-panorama'
        device_group: '{{ device_group }}'
        
    - name: From client backend subs to shared urls
      panos_security_rule:
        provider: '{{ palo_provider }}'
        rule_name: 'From client backend subs to shared urls - {{ client_name }}'
        description: '{{ ticket_id }}'
        source_zone: ['inside']
        destination_zone: ['outside']
        source_ip: ['{{ client_name }}-backend subs']
        destination_ip: ['any']
        category: ['shared-services-urls']
        tag_name: ['{{ tag_name }}']
        group_tag: '{{ tag_name }}'
        service: ['service-https']
        action: 'allow'
        group_profile: 'strict-security-profile'
        log_start: 'yes'
        location: 'before'
        existing_rule: '{{ existing_rule }}'
        log_setting: 'log-forwarding-panorama'
        device_group: '{{ device_group }}'
        
    - name: From dbm ec2 to v3locity sftp 
      panos_security_rule:
        provider: '{{ palo_provider }}'
        rule_name: 'From dbm ec2 to v3locity sftp - {{ client_name }}'
        description: '{{ ticket_id }}'
        source_zone: ['inside']
        destination_zone: ['outside']
        source_ip: ['{{ client_name }}-dbm.v3locitydev.com']
        destination_ip: ['sftp and sftpqa']
        tag_name: ['{{ tag_name }}']
        group_tag: '{{ tag_name }}'
        service: ['service-https']
        action: 'allow'
        group_profile: 'strict-security-profile'
        log_start: 'yes'
        location: 'before'
        existing_rule: '{{ existing_rule }}'
        log_setting: 'log-forwarding-panorama'
        device_group: '{{ device_group }}'      
        
    - name: From client backend subs to v3locitydev.com
      panos_security_rule:
        provider: '{{ palo_provider }}'
        rule_name: 'From client backend subs to v3locitydev.com - {{ client_name }}'
        description: '{{ ticket_id }}'
        source_zone: ['inside']
        destination_zone: ['outside']
        source_ip: ['{{ client_name }}-backend subs']
        destination_ip: ['any']
        category: ['v3locitydev.com']
        tag_name: ['{{ tag_name }}']
        group_tag: '{{ tag_name }}'
        service: ['service-https']
        action: 'allow'
        group_profile: 'strict-security-profile'
        log_start: 'yes'
        location: 'before'
        existing_rule: '{{ existing_rule }}'
        log_setting: 'log-forwarding-panorama'
        device_group: '{{ device_group }}'
        
    - name: From client backend subs to ftp2.vitechinc.com
      panos_security_rule:
        provider: '{{ palo_provider }}'
        rule_name: 'From client backend subs to ftp2.vitechinc.com - {{ client_name }}'
        description: '{{ ticket_id }}'
        source_zone: ['inside']
        destination_zone: ['outside']
        source_ip: ['{{ client_name }}-backend subs']
        destination_ip: ['ftp2.vitechinc.com']
        category: ['any']
        tag_name: ['{{ tag_name }}']
        group_tag: '{{ tag_name }}'
        service: ['tcp-22']
        action: 'allow'
        group_profile: 'strict-security-profile'
        log_start: 'yes'
        location: 'before'
        existing_rule: '{{ existing_rule }}'
        log_setting: 'log-forwarding-panorama'
        device_group: '{{ device_group }}'
        
    - name: From client backend subs to lacework urls
      panos_security_rule:
        provider: '{{ palo_provider }}'
        rule_name: 'To lacework urls from data subs - {{ client_name }}'
        description: '{{ ticket_id }}'
        source_zone: ['inside']
        destination_zone: ['outside']
        source_ip: ['{{ client_name }}-backend subs']
        destination_ip: ['any']
        category: ['lacework-urls']
        tag_name: ['{{ tag_name }}']
        group_tag: '{{ tag_name }}'
        service: ['service-https']
        action: 'allow'
        group_profile: 'strict-security-profile'
        log_start: 'yes'
        location: 'before'
        existing_rule: '{{ existing_rule }}'
        log_setting: 'log-forwarding-panorama'
        device_group: '{{ device_group }}'   